version: 2.1

jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: cat README
          command: cat README.md

workflows:
  spin_up_environment:
    jobs:
      - myjob
