version: 2.1

jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: something
          command: echo "hello"

workflows:
  end_to_end_tests:
    jobs:
      - myjob

